# Generated by Django 6.0.5 on 2026-06-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('network_admin',
                     'Network Administrator'),
                    ('client_manager',
                     'Client Manager')],
                default='client_manager',
                max_length=20),
        ),
    ]
