# Generated by Django 6.0.5 on 2026-05-26 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('cycle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='users.organization')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='DataUsageRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_consumed_mb', models.DecimalField(decimal_places=2, help_text='Data consumed in megabytes', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(help_text='When the usage actually occurred (may differ from timestamp)')),
                ('source', models.CharField(default='celery_task', help_text='Source of the usage data (e.g., celery_task, manual_entry, api_import)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('billing_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='usage.billingcycle')),
                ('sim_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='inventory.simcard')),
            ],
            options={
                'verbose_name': 'Data Usage Record',
                'verbose_name_plural': 'Data Usage Records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sim_card', '-recorded_at'], name='usage_datau_sim_car_173864_idx'), models.Index(fields=['billing_cycle', '-recorded_at'], name='usage_datau_billing_2f7335_idx')],
            },
        ),
    ]
