# Generated by Django 6.0.5 on 2026-05-20 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APN',
            fields=[
                ('apn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('apn_string', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('authentication_type', models.CharField(choices=[('none', 'None'), ('pap', 'PAP'), ('chap', 'CHAP'), ('pap_chap', 'PAP or CHAP')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apns', to='users.organization')),
            ],
            options={
                'verbose_name': 'APN',
                'verbose_name_plural': 'APNs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SIMCard',
            fields=[
                ('sim_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iccid', models.CharField(max_length=22, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated'), ('lost', 'Lost/Stolen')], default='available', max_length=20)),
                ('carrier', models.CharField(max_length=100)),
                ('network_type', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G/LTE'), ('5G', '5G')], default='4G', max_length=10)),
                ('data_limit_mb', models.IntegerField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('apn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='inventory.apn')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='users.organization')),
            ],
            options={
                'verbose_name': 'SIM Card',
                'verbose_name_plural': 'SIM Cards',
                'ordering': ['-date_created'],
            },
        ),
    ]
