# Generated by Django 6.0.5 on 2026-06-03 08:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_data_limit_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apn',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apn',
            name='username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
