# Generated by Django 6.0.5 on 2026-06-05 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_apn_password_alter_apn_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='iccid',
            field=models.CharField(help_text='ICCID must be 19-20 digits (numeric only)', max_length=22, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_iccid', message='ICCID must be 19-20 digits', regex='^\\d{19,20}$')]),
        ),
    ]
